- hosts: all
  become: true
   
  tasks:

    - name: Update apt cache (Debian)
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install Git (Debian)
      ansible.builtin.apt: 
        name: git
        state: latest
      when: ansible_os_family == "Debian"

    - name: Install Git (Fedora)
      ansible.builtin.dnf:
        name: git
        state: latest
      when: ansible_os_family == "RedHat"
